version: '3.5'
services:
    router-proxy:
        image: router-proxy
        build: .
        networks:
            - web
        labels:
            - traefik.enable=true
            - traefik.http.routers.router.rule=Host(`router.jamesjohnson.io`)
            - traefik.http.routers.router.entryPoints=web
            - traefik.http.routers.router.middlewares=redirect@file
            - traefik.http.routers.router-https.rule=Host(`router.jamesjohnson.io`)
            - traefik.http.routers.router-https.entryPoints=websecure
            - traefik.http.routers.router-https.tls=true
            - traefik.http.routers.router-https.tls.certresolver=myhttpchallenge
networks:
    web:
        external: true
